name: Labeler
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 25 * *'

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v2
    - name: Running
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
